#!/usr/bin/env node
// Rename the project across every tracked file. Run once, right after cloning the skeleton.
//
//   node scripts/rename-project.mjs acme-pos                  # title becomes "Acme Pos"
//   node scripts/rename-project.mjs acme-pos --title "Acme POS"
//   node scripts/rename-project.mjs acme-pos --dry-run        # report only
//
// Afterwards: pnpm install (rewrites the lockfile), then lint, typecheck, and test.
import { spawnSync } from 'node:child_process';
import { readFileSync, writeFileSync } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const args = process.argv.slice(2);
const dryRun = args.includes('--dry-run');
const titleFlag = args.indexOf('--title');
const titleArg = titleFlag >= 0 ? args[titleFlag + 1] : undefined;
const name = args.find((arg, i) => !arg.startsWith('--') && i !== titleFlag + 1);

if (!name || !/^[a-z][a-z0-9]*(-[a-z0-9]+)*$/.test(name) || (titleFlag >= 0 && !titleArg)) {
  console.error('Usage: node scripts/rename-project.mjs <kebab-case-name> [--title "Display Name"] [--dry-run]');
  process.exit(1);
}

const words = name.split('-');
const title = titleArg ?? words.map((word) => word[0].toUpperCase() + word.slice(1)).join(' ');
const snake = words.join('_');

// Longest first, so a short pattern never eats part of a longer one.
// The GhUiResolver identifier in packages/ui is left as it is.
const replacements = [
  ['GH Project Skeleton', title],
  ['gh-project-skeleton', name],
  ['db_project_skeleton', `db_${snake}`],
  ['GH-Skeleton', title.replace(/\s+/g, '-')],
  ['GH Skeleton', title],
  ['gh-skeleton', name],
  ['gh_skeleton', snake],
];

// The lockfile is regenerated by pnpm install; this script and its skill keep the old names as patterns.
const skip = new Set(['pnpm-lock.yaml', 'scripts/rename-project.mjs', '.claude/skills/rename-project/SKILL.md']);

const git = (gitArgs) => spawnSync('git', gitArgs, { cwd: root, encoding: 'utf8' });
const listed = git(['ls-files', '-z']);
if (listed.status !== 0) {
  console.error('Not a git repository: the file list comes from git ls-files.');
  process.exit(1);
}

const apply = (text) => replacements.reduce((result, [from, to]) => result.split(from).join(to), text);

let changedFiles = 0;
let renamedFiles = 0;

for (const file of listed.stdout.split('\0').filter(Boolean)) {
  if (skip.has(file)) continue;
  const absolute = path.join(root, file);

  let buffer;
  try {
    buffer = readFileSync(absolute);
  } catch {
    continue; // deleted in the working tree, or a broken symlink
  }

  // A NUL byte means a binary file.
  if (!buffer.includes(0)) {
    const before = buffer.toString('utf8');
    const after = apply(before);
    if (after !== before) {
      changedFiles += 1;
      console.log(`edit    ${file}`);
      if (!dryRun) writeFileSync(absolute, after);
    }
  }

  const renamed = apply(file);
  if (renamed !== file) {
    renamedFiles += 1;
    console.log(`rename  ${file} -> ${renamed}`);
    if (!dryRun) git(['mv', file, renamed]);
  }
}

console.log(
  `\n${dryRun ? 'Would change' : 'Changed'} ${changedFiles} files and ${dryRun ? 'rename' : 'renamed'} ${renamedFiles}. ` +
    `Name: ${name}. Title: ${title}. Database: db_${snake}.`,
);
if (!dryRun) console.log('Next: pnpm install, then pnpm --filter <workspace> typecheck for each app.');
